batch_type: numel
batch_bins: 3200000
accum_grad: 1
max_epoch: 600
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 256
    normalize_before: false
    freeze_finetune_updates: 1000
    # if use espent-trained model
    hubert_url: espnet
    hubert_dir_path: /nlsasfs/home/nltm-pilot/arunk/espnet_arun/espnet/egs2/librispeech/ssl_asr_scratch/exp/asr_hubert_pretraining_scratch_libri360_lre-4/checkpoints_backup/101epoch.pth

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00002
    
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

unused_parameters: true

frontend: null

normalize: null

specaug: null
